---
# bootloader GRUB - BIOS + UEFI, os-prober NYALA (dualboot kedetect)
efiBootLoader: "grub"
kernel: "linux-lts"
timeout: "10"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
installPath: ""
efiPartition: ""
