---
# displaymanager: SDDM + autologin user hasil install.
displaymanagers:
    - sddm
basicSetup: false
sysusersSetup: true
sddm:
    defaultDesktopEnvironment:
        executable: "plasmashell"
        desktopFile: "plasma.desktop"
