---
# packages: BERSIHIN live-only dari sistem hasil install.
# calamares + config + live tools JANGAN ikut keinstall.
try_remove:
    - calamares
    - calamares-config-koppie
    - archiso
    - mkinitcpio-archiso
    - yay
    - squashfs-tools
