---
# partition: EFI + GRUB, offline. os-prober aktif via grubcfg.
efiSystemPartition: "/boot/efi"
enableLuks: false
allowManualPartitioning: true
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]
