---
# Koppie Linux Calamares settings v1 (OFFLINE, GRUB, BIOS+UEFI. BELUM DITES.)
modules-search: [ local ]

instances: []

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - bootloader
  - packages
  - shellprocess
  - displaymanager
  - networkcfg
  - hwclock
  - services
  - grubcfg
  - removeuser
  - umount
- fail:
  - umount

branding: koppie
prompt-install: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
