---
# users: user baru di sistem hasil install (wheel = sudo).
defaultGroups:
    - audio
    - floppy
    - log
    - network
    - optical
    - power
    - scanner
    - storage
    - video
    - wheel
    - users
autologinGroup: autologin
doReusePassword: false
