---
# users: user baru di sistem hasil install (live user dihapus via removeuser).
defaultGroups:
    - audio
    - floppy
    - log
    - network
    - optical
    - power
    - scanner
    - storage
    - video
    - wheel
    - users
autologinGroup: autologin
doReusePassword: false
availableShells: [ /bin/bash, /bin/zsh ]
